src/Entity/Accounts.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\AccountsRepository")
 */
class Accounts
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $Client;

    /**
     * @ORM\Column(type="integer")
     */
    private $Balance;

    /**
     * @ORM\Column(type="datetime")
     */
    private $Last_Operation;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    //public $modification_balance;

    //public $is_added;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getClient(): ?string
    {
        return $this->Client;
    }

    public function setClient(string $Client): self
    {
        $this->Client = $Client;
        return $this;
    }

    public function getBalance(): ?int
    {
        return $this->Balance;
    }

    public function setBalance(int $Balance): self
    {
        $this->Balance = $Balance;

        return $this;
    }

    public function getLastOperation(): ?\DateTimeInterface
    {
        return $this->Last_Operation;
    }

    public function setLastOperation(\DateTimeInterface $Last_Operation): self
    {
        $this->Last_Operation = $Last_Operation;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;
        return $this;
    }

    public function getFormatedBalance(): string
    {
        $add = '';

        if($this->getBalance() >= 0){
            $add = '+';
        }
        return $add.number_format($this->getBalance(), 0, '', ' ');
    }

    public function getColorOfDisplay(): string
    {
        return $this->getBalance() >= 0 ? "text-success" : "text-danger";
    }

    public function isOutOfRange():bool
    {
        return abs($this->getBalance()) > 2000000000;
    }
}

src/Controller/AccountsController.php
<?php

namespace App\Controller;

use App\Entity\Accounts;
use App\Form\AccountFormType;
use App\Repository\AccountsRepository;
use Doctrine\Common\Persistence\ObjectManager;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class AccountsController extends AbstractController
{
    /**
     * @var AccountsRepository
     */
    private $repository;
    /**
     * @var ObjectManager
     */
    private $em;

    public function __construct(AccountsRepository $repository, ObjectManager $em)
    {
        $this->repository = $repository;
        $this->em = $em;
    }

    /**
     * @Route("/accounts", name="accounts")
     * @return Response
     */
    public function index(): Response
    {
        $user = $this->getUser();
        $account = $this->repository->findBy(['Client' => $user->getId()]);
        $nbr_accounts = sizeof($account);

        return $this->render('accounts/index.html.twig', [
            'accounts' => $account,
            'user' => $user,
            'nbr_accounts' => $nbr_accounts,
        ]);
    }

    /**
     * @Route("/accounts/edit/{id}", name="edit.accounts", methods="GET|POST")
     * @param Accounts $account
     * @return Response
     */
    public function edit(Accounts $accounts, Request $request)
    {
        if($accounts->getClient() == $this->getUser()->getId()) {
            $form = $this->createForm(AccountFormType::class, $accounts);
            $form->handleRequest($request);

            if ($form->isSubmitted() && $form->isValid()) {

                $transactionAmount = $request->request->get('transactionAmount');
                if($request->request->get('ActionType') == "debit")
                {
                    $transactionAmount *= -1;
                }

                $accounts->setBalance($accounts->getBalance()+$transactionAmount);

                if($accounts->isOutOfRange())
                {
                    $this->addFlash('error', 'Vous ne pouvez pas allez au-delas de ± 2 Milliards de $ sur un même compte...    ...ce qui est déjà pas mal');
                    return $this->redirectToRoute('accounts');
                }

                $accounts->setLastOperation(new \DateTime());
                $this->em->flush();
                $this->addFlash('success', 'Le compte a été mis à jour correctement.');
                //return new Response('<body></body>');
                return $this->redirectToRoute('accounts');
            }

            return $this->render('accounts/edit.html.twig', [
                'account' => $accounts,
                'form' => $form->createView(),
            ]);
        }
        else{
            $this->addFlash('error', 'Vous ne pouvez pas modifier ce compte.');
            return $this->redirectToRoute('accounts');
        }
    }


    /**
     * @Route("/accounts/new", name="new.accounts")
     * @return Response
     */
    public function new(Request $request)
    {
        $account = new Accounts();
        $form = $this->createForm(AccountFormType::class, $account);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid())
        {
            if($account->isOutOfRange())
            {
                $this->addFlash('error', 'Vous ne pouvez pas allez au-delas de ± 2 Milliards de $ sur un même compte...    veuillez réessayer');
                return $this->redirectToRoute('accounts');
            }
            $account->setLastOperation(new \DateTime());
            $account->setClient($this->getUser()->getId());
            $this->em->persist($account);
            $this->em->flush();
            $this->addFlash('success', 'Le compte a été crée avec succès.');
            return $this->redirectToRoute('accounts');
        }

        return $this->render('accounts/new.html.twig', [
            'account' => $account,
            'form' => $form->createView(),
        ]);
    }


    /**
     * @Route("/accounts/edit/{id}", name="delete.accounts", methods="DELETE")
     * @param Accounts $account
     * @return RedirectResponse
     */
    public function delete(Accounts $account)
    {
        if($account->getClient() == $this->getUser()->getId())
        {
            $this->em->remove($account);
            $this->em->flush();
            $this->addFlash('success', 'Le compte a été supprimé avec succès.');
        }
        else
        {
            $this->addFlash('error', 'Vous ne pouvez pas supprimer ce compte.');
        }
        return $this->redirectToRoute('accounts');
    }

    public function checkIfOutOfRange(Accounts $account)
    {
        if ($account->isOutOfRange()){

        }
        else{
            return null;
        }
    }

}

templates/accounts/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    Modification du compte
{% endblock %}

{% block body %}
    <div class="container mt-4">
        <h3>Modification du compte <span class="text text-primary">{{ account.name }}</span></h3>
        <br/>
        {{ form_start(form) }}
        <div class="">
            {{ form_row(form.name, {'label': 'Nom du compte','attr': {placeholder: ''}}) }}
        </div><br/>

        <div class="">
            {{ form_row(form.Balance, {'label': 'Modifer la balance','attr': {placeholder: ''}}) }}
            <small id="emailHelp" class="form-text text-muted text-left">Permet de forcer la balance du compte</small>
        </div>
        <br/><br/>

        <div class="bg-light p-4">
            <h5><i class="fas fa-exchange-alt"></i> | Appliquer une transaction</h5>
            <hr/>
        <div class="form-group">
            <label for="formGroupExampleInput">Montant (CAD)</label>
            <div class="input-group">
                <input type="number" value="0" class="form-control" required name="transactionAmount">
                <div class="input-group-append">
                    <span class="input-group-text">$ CAD</span>
                </div>
            </div>
        </div>



        <div class="form-check form-check-inline">
            <input class="form-check-input" type="radio" name="ActionType" id="inlineRadio1" value="credit" checked="checked">
            <label class="form-check-label" for="inlineRadio1"><span class="badge badge-success">CRÉDIT</span></label>

        </div>
        <div class="form-check form-check-inline">
            <input class="form-check-input" type="radio" name="ActionType" id="inlineRadio2" value="debit">
            <label class="form-check-label" for="inlineRadio2"><span class="badge badge-danger">DÉBIT</span></label>

        </div>
        </div>
        <br/>
        <a href="{{ path('accounts') }}" class="btn btn-secondary">Retour</a>
        <button class="btn btn-primary">Appliquer</button>
        {{ form_end(form) }}


    </div>
{% endblock %}

templates/accounts/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    Mes comptes
{% endblock %}

{% block nav_rigtht %}

        <a href="{{ path('home') }}" class="btn btn-secondary mr-3">Accueil du site</a>
        <a href="{{ path('security_logout') }}" class="btn btn-outline-secondary">Déconnexion</a>

{% endblock %}

{% block body %}



    <div class="container mt-4">
        <h1>Bonjour <span class="text text-primary">{{ user.getFirstname}} {{user.getName}}</span></h1>

        <hr/><br/>
        <div class="row">
            <div class="col">
                <h3 class="d-inline">Gestion des comptes <span class="badge badge-secondary">{{ nbr_accounts }}</span></h3>
            </div>
            <div class="col text-right">
                <a href="{{ path('new.accounts') }}" class="btn btn-primary d-inline" ><i class="fas fa-plus-circle"></i> Nouveau compte</a>

            </div>
        </div>

        {% for message in app.flashes('success') %}
            <br/>
            <div class="alert alert-success">{{ message }}</div>
        {% endfor %}
        {% for message in app.flashes('error') %}
            <br/>
            <div class="alert alert-danger">{{ message }}</div>
        {% endfor %}

        <style>
            .table > tbody > tr > td {
                vertical-align: middle;
            }
        </style>

        <table class="table table-striped mt-4 align-middle">
            <thead>
            <tr>
                <th>ID</th><th>Nom</th><th>Balance (CAD)</th><th>Dernière Opération</th><th>Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for account in accounts %}
                <tr>
                    <td>{{ account.id }}</td>
                    <td>{{ account.name }}</td>
                    <td class="font-weight-bold {{ account.colorOfDisplay }}">{{ account.formatedBalance }} $</td>
                    <td>{{ account.lastOperation|date("d/m/Y H:i:s", "America/New_York") }}</td>
                    <td>
                        <a href="{{ path('edit.accounts', {id: account.id}) }}" class="btn btn-secondary"><i class="fas fa-pen"></i> Modifier</a>

                        <form method="post" onsubmit="return confirm('Confirmez-vous la suppression de ce compte ?')" action="{{ path('edit.accounts', {id: account.id}) }}" style="display: inline-block">
                            <button class="btn btn-danger"><i class="fas fa-trash"></i> Supprimer</button>
                            <input type="hidden" name="_method" value="DELETE">
                        </form>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    <p>Time zone : America/New_York</p>
    </div>

{% endblock %}

templates/accounts/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    Nouveau compte
{% endblock %}

{% block body %}
    <div class="container mt-4">
        <h3>Création d'un nouveau compte</h3>
        <br/>
        {{ form_start(form) }}
        <div class="">
            {{ form_row(form.name, {'label': 'Nom du compte','attr': {placeholder: ''}}) }}
        </div><br/>

        <div class="">
            {{ form_row(form.Balance, {'label': 'Balance initiale $ (CAD)','attr': {placeholder: ''}}) }}
        </div>
        <br/>

        <a href="{{ path('accounts') }}" class="btn btn-secondary">Retour</a>
        <button class="btn btn-primary">Appliquer</button>
        {{ form_end(form) }}
    </div>
{% endblock %}